### PR TITLE
Extender was unstable

### PR DESCRIPTION
**Pull request by paul-777**
The extender was unstable due to threads accessing UI components. Still
has some issues when streaming.  Overscan was not supported on all
pages. Add click indicator as page transitions can be slow on xbox and you end up hitting the button again to make sure then double skipping back.

### CODE REVIEW

**Comment by ebr11** [comment]
Please break into smaller pieces but, first, we need to eliminate all breaking changes.  This means no changes to the signature of any public or protected methods or properties.  I suspect, once this is rectified, the change set will get much smaller as well.  Thanks.

**Comment by paul-777** [comment]
That isn't going to be practical,or necessary, the public methods are only used within this project afterall so there is no reason not to allow refactoring. The basic threading model has been allowed to get misused all over the place so a refactoring is necesary to tighten up on that. The changes are actually fairly small but they do need carrying through the code base to ensure we actually fix the issues and also provide a framework where people won't recreate the issues again. It has taken me about 50hours of debugging to get this far and unfortunately the time I have to spend on this has expired, my wife only has a limited patience for such things.




-------- Original Message --------

**Comment by ebr11** [comment]
It is necessary because those properties and methods are used outside of the project.  Plug-ins can extend the object model and inherit from BaseModelItem.

You can change the implementation you just can't change the signature of the method.  That will still accomplish the goal.

**Comment by ebr11** [comment]
But, if you don't have any more time to do this, that's okay.  I'll take the UI thread modifications and roll them into the next major release of MBC manually.  Thanks for your efforts.

**Comment by paul-777** [comment]
Ah, yes, I see, I can see the couple of method renames that would cause issues, I'll try and get some time to rename them back and check for other cases, as you say this will shrink the change. In the future it may be worth adding newly named ones and marking the old ones obsolete at some point as currently they are the same as the MS functions that should only be called from the UI and having them named the same makes finding misuses much harder. The xboxes seem to be far more sensitive to bad threading onto the UI than the native interface, something to do with running slower over the remote connection I guess.



-------- Original Message --------

**Pull request closed without merging**
