### PR TITLE
Display audio item details when playing from a remote stream

### PR DESCRIPTION
**Pull request by softworkz**

### CODE REVIEW

**Comment by softworkz** [comment]
When a user starts playing a stream URL in Emby for WMC, the result is currently looking like this:

stream_playback_current

**Comment by softworkz** [comment]
=> No name, no artist, no duration, no image

**Comment by softworkz** [comment]
After endless hours of reverse engineering WMC and WMP code I finally found a way to make this work.
Using an ASX file to specify title and author was the easy part. The tricky thing was finding a way to specify an album/cover image.

The solution I found is probably not publically known. At least I didn't find any references for the relevant keywords. But actually this is a supported and documented method, once you realize that PARAM elements in ASX files  correspond to metadata attributes in the Windows Media Player API....

**Comment by softworkz** [comment]
So, here's the result (just as it's expected to be):

stream_playback_richdata

**Comment by ebr11** [comment]
1) What is a source of this type of content so that I can test?

2) Have you fully tested this with other playback items to be sure there are no side-effects?

**Comment by softworkz** [comment]
1) This affects items of type "Song" that are having a http(s) URL as File property.
It also affects playback of multiple items (PlayableItem with multiple MediaItems), but only if the previous condition is met for ALL items

In my case the source were audio items from the new SoundCloud channel plugin I have developed.
But it works for any streaming audio content. Recently I also successfully tested this with the TuneIn plugin.

2) Yes I did. Regular items (non-streaming) are not affected. Non-Song items aren't affected anyway.
The last thing I checked was playback of audio items in case EmbyForWMC is installed on a different computer than EmbyServer (and no UNC paths are used): For videos, EmbyForWMC has implemented a fallback to streaming in these cases,  but not for audio items. Thus, there was nothing to test for this case...

**Comment by softworkz** [comment]
Thanks for looking into it. A few more hints:

- I also commited changes to "CreateWplPlaylist". These are not neccessarily required at this time since WPL playlists are used for videos only. But this code shows some properties that can be set through the "friendlyData" parameter which aren't documented anywhere, so I left it in
- In a few places I added a check for https: in addition to http: since SoundCloud for example offers streaming via https
- The reason for the change to the "UnwatchedCount" handling was an infinite loop I encountered with SoundCloud. But even for channel content with limited depth this could have the effect to perform a full retrieval of the subtree. I fixed this for channel folders, but I would suggest to double-check the behaviour for normal library content as well!

**Pull request merged**
